### ISSUE TITLE
tocsv does not preserve column order of sqlalchemy table

### ISSUE THREAD

**Issue by kristi** [alimanfoo/petl#322] opened 2015-03-10 19:28 UTC

**Comment by alimanfoo** [comment] 2015-03-19 16:07
Hi @krist, apologies for slow response, thanks for submitting this. I'm not sure the problem would be in tocsv() specifically, if the column order is not preserved then the problem is more likely to be in the extract function, which I'm guessing is fromdb()? Could you provide the snippet of code used to generate this problem? Thanks.

**Comment by alimanfoo** [comment] 2015-04-20 14:46
Hi @kristi, I'm going to close this but feel free to re-open if you can isolate the problem.

**Closed by alimanfoo** 2015-04-20 14:46 UTC
